### ISSUE TITLE
Passthrough performance

### ISSUE THREAD

**Issue by polachok** [LTD-Beget/syncookied#1]
Passthrough performance with no filters is lower than expected (~8Mpps) on our test setup.

**Comment by pavel-odintsov** [comment]
It's could be related with used CPU. You could expect near zero overhead only with top notch Xeon CPUS (E5 v3+).

**Comment by polachok** [comment]
This is unlikely as we're using Xeon E5 2680v3. I guess it's some problem with implementation which only manifests itself in this mode (we get higher pps while doing syncookies).

**Comment by polachok** [comment]
Fixed by #40
