### ISSUE TITLE
AVX support need is unclear

### ISSUE THREAD

**Issue by trueneu** [LTD-Beget/syncookied#22]
It seems that syncookied cookie_hash() function (in `src/cookie.rs`) heavily depends on AVX support by CPU by default, and if there's none it results it 'invalid opcode' errors, which is pretty predictable.
We found that there are several variations of sha1_transform function which depend on various instruction sets. So we just commented the AVX version and uncommented SSE3. And it worked.

What I'd suggest is to include this information in README so people without AVX extensions won't have to research why it doesn't work and/or probably even make the default sha1_transform the most compatible one.

There's also a comment: 

> TODO: use cargo features or runtime detection to choose the fastest

I'd add to that '...the fastest among compatible' .

**Comment by polachok** [comment]
Please take a look at #23, what do you think?

**Comment by trueneu** [comment]
Looks awesome! Controllable by build flags and clear mention in the docs, much better this way than dirty source hacks. :)

**Comment by trueneu** [comment]
Thanks a lot.
