### ISSUE TITLE
Не компилируется

### ISSUE THREAD

**Issue by mountdevhands** [LTD-Beget/syncookied#29]
Здравствуйте!

Уточните, пожалуйста, почему может не компилироваться:
     Running `rustc /root/.cargo/git/checkouts/libpnet-ae38e659f18cc3c8/syncookied/pnet_macros/src/lib.rs --crate-name pnet_macros --crate-type lib -C opt-level=3 -g --cfg feature=\"syntex_syntax\" --cfg feature=\"with-syntex\" --cfg feature=\"default\" --cfg feature=\"syntex\" -C metadata=a683be57cc4c7cfe -C extra-filename=-a683be57cc4c7cfe --out-dir /usr/src/syncookied/target/release/deps --emit=dep-info,link -L dependency=/usr/src/syncookied/target/release/deps -L dependency=/usr/src/syncookied/target/release/deps --extern regex=/usr/src/syncookied/target/release/deps/libregex-a99351f81f55a22d.rlib --extern syntex_syntax=/usr/src/syncookied/target/release/deps/libsyntex_syntax-5a1d94417b53af6a.rlib --extern syntex=/usr/src/syncookied/target/release/deps/libsyntex-d786ed71bd2d7a6d.rlib --cap-lints allow`
/root/.cargo/git/checkouts/bounded-spsc-queue-da0656e60eed9ff6/with/src/lib.rs:2:1: 2:68 error: #[feature] may not be used on the stable release channel [E0554]
/root/.cargo/git/checkouts/bounded-spsc-queue-da0656e60eed9ff6/with/src/lib.rs:2 #![feature(heap_api, oom, alloc, box_syntax, optin_builtin_traits)]
                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `bounded-spsc-queue`.

Caused by:
  Process didn't exit successfully: `rustc /root/.cargo/git/checkouts/bounded-spsc-queue-da0656e60eed9ff6/with/src/lib.rs --crate-name bounded_spsc_queue --crate-type lib -C opt-level=3 -g --cfg feature="default" -C metadata=83cd369280c8532d -C extra-filename=-83cd369280c8532d --out-dir /usr/src/syncookied/target/release/deps --emit=dep-info,link -L dependency=/usr/src/syncookied/target/release/deps -L dependency=/usr/src/syncookied/target/release/deps --cap-lints allow` (exit code: 101)

Есть ли собранные deb и rpm-пакеты демона?

**Comment by PheonixS** [comment]
У вас Rust старый.Нужен Nighly branch.

curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly

**Comment by polachok** [comment]
@Louvremaster проблема решена?

**Comment by mountdevhands** [comment]
Да, спасибо, под Debian все ок.
