### ISSUE TITLE
port-forwarding probblem

### ISSUE THREAD

**Issue by Onepamopa** [LTD-Beget/syncookied#55]
Hello,

For some reason iptables port-forwarding doesn't work when syncookied is used to deliver the traffic.
Example:
iptables -t nat -A PREROUTING -i <iface> -p tcp -m tcp --dport 80 -j DNAT --to-destination :8080
The packet gets forwarded and immediately rejected (the web server replies with tcp-rst).

Any ideas ?

**Comment by polachok** [comment]
This is expected behavior (and it's mentioned in the FAQ: https://github.com/LTD-Beget/syncookied/wiki).
It happens because cookie has ports and IPs encoded into it and it turns invalid if you modify either before it hits cookie_v4_check() in tcp_input.
