### ISSUE TITLE
What's your code license?

### ISSUE THREAD

**Issue by pavel-odintsov** [LTD-Beget/syncookied#6]
Hello!

I could not find actual code license. Could you mention it explicitly?

**Comment by polachok** [comment]
We're reusing code from Linux kernel licensed under GPLv2, therefore whole project is GPLv2 if I understand its terms correctly.
Currently it's mentioned in Cargo.toml: 
https://github.com/LTD-Beget/syncookied/blob/master/Cargo.toml#L7
I'll add it into README

**Comment by pavel-odintsov** [comment]
Thanks!
